# Server Configuration
server:
  port: 8080

# Kafka Configuration
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-id

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
  file:
    name: logs/application.log

